### ISSUE TITLE
Minor strings update needed

### ISSUE THREAD

**Issue by delivrance** [ytaudiobot/ytaudiobot-l10n#130]
Hi guys, the renamed keys **file_info**, **file_info_button** and **share_button** were also slightly changed. Minor update needed.

"More info" -> "File info"
"Send to..." -> "Share"

Please try to keep **file_info_button** as short as possible.
As the example above, "File information" can be "File info" or "Information". You choose the best looking way in your language, just don't set it too wide.

- [x] 🇺🇸 **English**
- [x] 🇮🇹 **Italiano**
- [x] 🇪🇸 **Español**
- [ ] 🇧🇷 **Português**
- [x] 🇮🇱 **עברית**
- [x] 🇩🇪 **Deutsch**
- [ ] 🇫🇮 **Suomi**
- [ ] 🇬🇷 **Ελληνικά**
- [ ] 🇷🇴 **Română** 
- [ ] 🇺🇿 **O'zbek**
- [ ] :indonesia: **Bahasa Indonesia**
- [ ] :tr: **Türkçe**
- [x] :cn: **简体中文**
- [x] :taiwan: **繁體中文**
- [ ] :saudi_arabia: **العربية**
- [ ] :jp: **日本語**
- [ ] :ukraine: **Українська**
- [ ] :fr: **Français**
- [x] 🏳️ : **Català**
- [x] :ru: **Русский**
- [ ] :azerbaijan: **Azərbaycanca**

**Comment by Ecron** [comment]
Done for Catalan :+1:

**Comment by LoGazer** [comment]
Also done for "Deutsch" (German ) #159

**Comment by Hiruy28** [comment]
I can do amharic
