### ISSUE TITLE
Latine (la_LA)

### ISSUE THREAD

**Issue by tychontychon** [ytaudiobot/ytaudiobot-l10n#140]

**Comment by delivrance** [comment]
Uh, this might be funny. Go ahead if you like!

**Comment by delivrance** [comment]
Not sure if still interested so I'm closing this, reopen if you are!

**Comment by tychontychon** [comment]
I am very interested — but I still cannot understand how to translate here on GitHub, that's because I left translation :disappointed:

**Comment by delivrance** [comment]
Please, have a look here first: https://github.com/ytaudiobot/ytaudiobot-l10n#localization-guidelines
Then, if you have any specific question, feel free to ask!
