### ISSUE TITLE
Idea for a command to get the latest X videos from your subscriptions

### ISSUE THREAD

**Issue by orschiro** [ytaudiobot/ytaudiobot-l10n#148]
Just an idea I had. Looking forward to what you think. 

I could imagine a handy command to quickly fetch the latest X (e.g. 5) videos from your Youtube subscriptions. 

This would be a huge time saver for me since I could get the latest videos that interested me ready for the day to carry with me with just a single command! :-)

What do others think?

**Comment by Ecron** [comment]
Mmm, I guess it could be handy for some cases, but as the videos I watch on my subscriptions are not only audio-related (they have an important video-related content) it won't be useful for me. It would be only useful for podcasts, music video, etc. 

So not an option I would use.

**Comment by orschiro** [comment]
Got you. Thanks. Other opinions?

El 31 de agosto de 2017 17:54:21 CEST, Ecron <notifications@github.com> escribió:
>Mmm, I guess it could be handy for some cases, but as the videos I
>watch on my subscriptions are not only audio-related (they have an
>important video-related content) it won't be useful for me. It would be
>only useful for podcasts, music video, etc. 
>
>So not an option I would use.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ytaudiobot/ytaudiobot-l10n/issues/148#issuecomment-326340491

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by delivrance** [comment]
Hi! Again, this is something that goes a bit beyond the very purpose of the bot, which I'd like to keep simple and easy to use. Multiple file fetching is a frequently requested feature, but it's unlikely I will add something similar.

**Comment by orschiro** [comment]
Ok thanks :)

El 6 de septiembre de 2017 07:21:38 CEST, Dan <notifications@github.com> escribió:
>Hi! Again, this is something that goes a bit beyond the very purpose of
>the bot, which I'd like to keep simple and easy to use. Multiple file
>fetching is a frequently requested feature, but it's unlikely I will
>add something similar.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ytaudiobot/ytaudiobot-l10n/issues/148#issuecomment-327377784

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.
