### ISSUE TITLE
Greek (el_GR)

### ISSUE THREAD

**Issue by stamsarger** [ytaudiobot/ytaudiobot-l10n#26]
Working on Greek! 🇬🇷

**Comment by delivrance** [comment]
Great!

**Comment by delivrance** [comment]
Hey, contact me on Telegram so that we can test if all the translated strings fit!

**Comment by stamsarger** [comment]
I can't, I am limited 😭 The limit ends in two days though (13/12/2016 at 20:30), should I message you then?
Or if we can't wait, message me at @stamsarger

**Comment by delivrance** [comment]
Don't worry. We'll get in touch when you can.
