### ISSUE TITLE
Russian (ru_RU)

### ISSUE THREAD

**Issue by evgfilim1** [ytaudiobot/ytaudiobot-l10n#40]

**Comment by delivrance** [comment]
Hello there!

**Comment by evgfilim1** [comment]
Oh, sorry, I was busy. I'm working at translation now

**Comment by delivrance** [comment]
Hi! Don't worry, take your time

**Comment by evgfilim1** [comment]
I have a problem. If there are different forms for the next word after numeral in my language, what should I do?

**Comment by delivrance** [comment]
Which string are you referring about exactly?

**Comment by evgfilim1** [comment]
@delivrance about "added_*_ago"

**Comment by delivrance** [comment]
Are you saying that there are more than 3 variants in Russian? Please explain more in detail.

You basically need to build a sentence with a meaning for 0, 1 and >1 items:
In this specific case the `0` is not so relevant, but you need to make it like:

`Added 0 seconds/minutes/hours/... ago`,
`Added 1 second/minute/hour/... ago`,
`Added 13 seconds/minutes/hours`

**Comment by evgfilim1** [comment]
@delivrance, yes, I mean this.
For 0, 5-20, 25-30, 35-40, etc. we have one form
For 1, 21, 31, etc. we have another form
For 2-4, 22-24, 32-34, etc. we have one more form

**Comment by evgfilim1** [comment]
@delivrance, okay, thanks
