### ISSUE TITLE
Uzbek (Latin) - Uzbekistan Lt_uz_UZ

### ISSUE THREAD

**Issue by HusanboyBayern** [ytaudiobot/ytaudiobot-l10n#43]
I am Husanboy, developer!

**Comment by delivrance** [comment]
Hi there!

**Comment by HusanboyBayern** [comment]
Hi

**Comment by delivrance** [comment]
Take your time. When you can, send me a PR with the new translation and we will test it in a test bot to see if the strings fit together

**Comment by HusanboyBayern** [comment]
How can I download PR. Please give clear instructions to get the file that should be modified.

**Comment by delivrance** [comment]
I've just noticed you are new to GitHub! As stated in the [guide](https://github.com/ytaudiobot/ytaudiobot-l10n#creating-a-new-localization) the file you need to look at is [en_US.json](https://github.com/ytaudiobot/ytaudiobot-l10n/blob/master/messages/en_US.json).

PR means Pull Request and is a method of submitting contributions to a project.

The easiest way for you is to create a new file inside the `messages` folder named `Lt_uz_UZ.json`, copy the content of the English source and start translating it. Or you can manually fork the project and clone the repository to your computer.

There are some nice tutorials on GitHub to get started; for project contributions like this you may also want to read here: https://guides.github.com/activities/contributing-to-open-source/#contributing.

**Comment by HusanboyBayern** [comment]
Yeah I found 'em. Thanks.  Started the project!  I'll finish soon!

**Comment by delivrance** [comment]
Translation added, but some fixes are needed now. Please contact me on Telegram I'll give you access to a test bot to test the new language: [@haskell](https://telegram.me/haskell)

**Comment by delivrance** [comment]
Thank you!
