### ISSUE TITLE
Updated Turkish Language

### ISSUE THREAD

**Issue by binzet** [ytaudiobot/ytaudiobot-l10n#78]
The letters are corrupted due to incorrect encoding. So I corrected all of them.
Encoding is UTF-8. 

[new Turkish.txt](https://github.com/ytaudiobot/ytaudiobot-l10n/files/656032/new.Turkish.txt)

**Comment by delivrance** [comment]
Great! Thank you.

**Comment by delivrance** [comment]
Changes merged! For any other updates you can also directly edit the file here: https://github.com/ytaudiobot/ytaudiobot-l10n/edit/master/messages/tr_TR.json and then click "Propose changes" to open a new PR.

**Comment by binzet** [comment]
Ok, thanks.

**Comment by delivrance** [comment]
Thanks to you!
