### ISSUE TITLE
Turkish language problem 

### ISSUE THREAD

**Issue by binzet** [ytaudiobot/ytaudiobot-l10n#87]
Sorry but not available Turkish in bot.

**Comment by delivrance** [comment]
Yes, tr_TR is not live on the main bots yet because we have to test the translation first! Either you or https://github.com/EypCnn must contact me on telegram to discuss and test about the translation and see if every string fit together

**Comment by binzet** [comment]
I want to testing.  this my telegram: /ilkerbinzet

**Comment by stamsarger** [comment]
You can't, only the translator can test it afaik
And you have to contact /haskell first

**Comment by delivrance** [comment]
:tr: Türkçe (tr_TR) is now live on main bots! Thank you guys!
