### ISSUE TITLE
fa_IR Farsi - Iran

### ISSUE THREAD

**Issue by kamy77** [ytaudiobot/ytaudiobot-l10n#93]
im going to translate it to persian

**Comment by delivrance** [comment]
Hi there! Why did you close the Issue?

**Comment by kamy77** [comment]
because i was confused i just can translate not coding or github things,
give me the things that need to translate and ill give them to you

2016-12-30 19:26 GMT+03:30 Dan <notifications@github.com>:

**Comment by delivrance** [comment]
Hi! Everything is explained in the main page of the [project](https://github.com/ytaudiobot/ytaudiobot-l10n).

You can download the English source file [en_US.json](https://github.com/ytaudiobot/ytaudiobot-l10n/blob/master/messages/en_US.json) and start translating the strings. Please follow the localization guidelines!
Next step, create a new file inside the project: open https://github.com/ytaudiobot/ytaudiobot-l10n/new/master/messages and paste the content of your language file, give it the name `fa_IR.json` and press "Propose new file" at the bottom.

If you need any further help feel free to ask here!
